### PR TITLE
New and updated classes from knockout mode

### PR DESCRIPTION
**Pull request by MrPh1l**
Added
- CarDemoActor_TA -> Add a mesh that demos cars on contact. No need for trigger volumes + kismet
- PlayerStart_Platform_TA -> Can replace PlayerStart_TA. A player start with a mesh. Includes a timer config to despawn after a certain time (5 sec. default)
- CrowdSounds_Knockout_TA -> New sound config for knockout
- CrowdSoundsBase_TA

Updated
- CrowdSounds_TA

### CODE REVIEW

**Comment by ghostrider-05** [comment]
The new class `OutOfWorldVolume_TA` also seems to be related to knockout. I haven't tested the effects / how it differs from the normal volume, but could be interesting.

Same for `CameraVolume_KnockOut_TA`

**Comment by MrPh1l** [comment]
For `OutOfWorldVolume_TA`, It requires the interface IDisposable for the line `var() array< class<GFxClubAction_TA> > TouchTypes;`. I wasn't able to get the interface to compile.

For `CameraVolume_KnockOut_TA`, it is not placeable in the class and I haven't tested enough to include it. I don't want to include something without knowing what it does and being able to make it work first.

Feel free to update this pull request witch changes if you get those two to work.

**Comment by ghostrider-05** [comment]
> For `OutOfWorldVolume_TA`, It requires the interface IDisposable for the line `var() array< class<GFxClubAction_TA> > TouchTypes;`. I wasn't able to get the interface to compile.

Also not with the dummy class version: https://github.com/RocketLeagueMapmaking/RL-Dummy-Classes/blob/master/Core/Classes/IDisposable.uc?
> For `CameraVolume_KnockOut_TA`, it is not placeable in the class and I haven't tested enough to include it. I don't want to include something without knowing what it does and being able to make it work first.

Oh lol, didn't realize `Volume` was not placeable

**Comment by MrPh1l** [comment]
> Oh lol, didn't realize Volume was not placeable

From what I tested so far, it seems like this volume gets created and managed automatically when in the knockout mode. We could test it with `placeable` later on and see how it reacts though. It might be useful in some maps who knows.

**Comment by MrPh1l** [comment]
> Also not with the dummy class version: https://github.com/RocketLeagueMapmaking/RL-Dummy-Classes/blob/master/Core/Classes/IDisposable.uc?

Turns out this works. I'm not sure why I didn't have this version.
I'll push some new changes to include `OutOfWorldVolume_TA`.

**Comment by ghostrider-05** [comment]
I tested again and was able to recompile on a new install, so added the class. I think the best is to leave the camera volume out for now

**Comment by ghostrider-05** [comment]
Updated some older kismet nodes in this pr as well, let me know if you can recompile these classes

**Comment by MrPh1l** [comment]
I was able to compile your classes on my end. You can complete the pull request.

**Pull request merged**
